### ISSUE TITLE
Install hook fails on juju 2.0-beta1 (agent 2.0-alpha2)

### ISSUE THREAD

**Issue by tomck** [juju/juju-gui-charm#47] opened 2016-03-10 15:15 UTC
On the azure-provider, the first thing I set up after bootstrapping was juju-gui. However, the install hook would fail. I tried debugging it, and here's my output:

```
root@machine-1:/var/lib/juju/agents/unit-juju-gui-0/charm# ./hooks/install 
Traceback (most recent call last):
  File "./hooks/install", line 49, in <module>
    from charmhelpers import (
ImportError: cannot import name get_config
```

The log files don't seem to contain any useful data, and I'm not sure what from them would be considered insecure to share (api keys etc).

**Comment by hatched** [comment] 2016-03-10 15:20
Possible duplicate of https://github.com/juju/juju-gui-charm/issues/45

**Comment by bac** [comment] 2016-03-10 15:31
@tomck Can you tell me which version of the juju-gui charm you have?

**Comment by bac** [comment] 2016-03-10 15:54
@tomck Can you paste the output of 
```
juju status juju-gui
```
here please?

**Comment by tomck** [comment] 2016-03-10 15:57
```
PB-Macmini:ssh pinebiotech$ juju status juju-gui
[Services] 
NAME       STATUS      EXPOSED CHARM                 
juju-gui   maintenance true    cs:trusty/juju-gui-50 

[Units]    
ID         WORKLOAD-STATE AGENT-STATE VERSION    MACHINE PORTS PUBLIC-ADDRESS MESSAGE                             
juju-gui/0 maintenance    executing   2.0-alpha2 1             168.61.x (install) installing charm software 

[Machines] 
ID         STATE   DNS            INS-ID    SERIES AZ 
1          started 168.61.x machine-1 trusty    
```

**Comment by bac** [comment] 2016-03-10 16:03
Thanks @tomck.  There is a known problem with juju-gui-50.  If you can redeploy you'll get the new one and it will work.

**Comment by bac** [comment] 2016-03-10 16:07
I'll leave this issue open until @tomck you can confirm `juju deploy juju-gui` now works for you and deploys -51.

**Comment by tomck** [comment] 2016-03-10 16:36
This issue is sorted, it does install and open. I can't login because show-controller is no longer a command, however, but that is a separate bug.

```
$ juju show-controller --show-passwords
ERROR unrecognized command: juju show-controller
```

**Comment by bac** [comment] 2016-03-10 17:05
@hatched could you provide @tomck with the new command?

**Comment by bac** [comment] 2016-03-10 18:26
@tomck This release of the juju gui is geared to the Juju 2 beta release which is coming out today.  The method for getting the username and password we document is for that version of juju. I don't have access to the alpha version you have.  You might try `juju api-info --password password`. I can't guarantee that it'll work but it might.

**Comment by mitechie** [comment] 2016-03-10 19:32
Sorry, yes. Please see the release notes and we've got a new beta coming
out today with more progress on the front.

https://lists.ubuntu.com/archives/juju/2016-February/006618.html

**Comment by hatched** [comment] 2016-03-10 22:05
The commands to get your credentials are as follows:
```
// Juju 1.x
juju api-info --password password

// Juju 2.0-beta1
juju show-controller --show-passwords
```
It's possible that you were using an older version of Juju 2.0. As @mitechie said, you should expect to see a new beta being released very soon.

**Closed** 2016-04-05 18:49 UTC
Labels: bug
